spring.datasource.url=jdbc:mysql://localhost:3506/yaksok
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=yaksokJwtSecretKeyForDevelopment1234567890abcdef
jwt.expiration-ms=86400000

dur.service-key=lc9jsdXUSgGW7NpRSWbeAgBlr%2FVHRPC9dnK9i6Ab5sQYprv%2FYitVPLisSKYK3H2z%2BqkWYafsOTMJmhvwN%2BnriQ%3D%3D
dur.base-url=https://apis.data.go.kr/1471000/DURPrdlstInfoService03/getUsjntTabooInfoList03